# Generated by Django 4.2.1 on 2023-06-04 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='venue',
            old_name='created',
            new_name='created_at',
        ),
    ]
