# Generated by Django 4.2.1 on 2023-06-11 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0003_rename_reservation_venue_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='venue',
            name='updated',
        ),
    ]
