# Generated by Django 4.2.1 on 2023-06-13 14:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0004_remove_venue_created_at_remove_venue_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venue',
            name='name',
            field=models.CharField(default='Tao', max_length=180),
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.CharField(default='Oat', max_length=180),
        ),
        migrations.AddField(
            model_name='venue',
            name='status',
            field=models.CharField(default='NEW', max_length=180),
        ),
        migrations.AddField(
            model_name='venue',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
